apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: mackerel-container-agent-sidecar-injector-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mackerel-sidecar-injector-controller-manager
  namespace: mackerel-container-agent-sidecar-injector-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mackerel-sidecar-injector-leader-election-role
  namespace: mackerel-container-agent-sidecar-injector-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mackerel-sidecar-injector-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mackerel-sidecar-injector-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mackerel-sidecar-injector-leader-election-rolebinding
  namespace: mackerel-container-agent-sidecar-injector-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mackerel-sidecar-injector-leader-election-role
subjects:
- kind: ServiceAccount
  name: mackerel-sidecar-injector-controller-manager
  namespace: mackerel-container-agent-sidecar-injector-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mackerel-sidecar-injector-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: mackerel-sidecar-injector-controller-manager
  namespace: mackerel-container-agent-sidecar-injector-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mackerel-sidecar-injector-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mackerel-sidecar-injector-proxy-role
subjects:
- kind: ServiceAccount
  name: mackerel-sidecar-injector-controller-manager
  namespace: mackerel-container-agent-sidecar-injector-system
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 75278439.mackerel.io
kind: ConfigMap
metadata:
  name: mackerel-sidecar-injector-manager-config
  namespace: mackerel-container-agent-sidecar-injector-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: mackerel-sidecar-injector-controller-manager-metrics-service
  namespace: mackerel-container-agent-sidecar-injector-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: mackerel-sidecar-injector-webhook-service
  namespace: mackerel-container-agent-sidecar-injector-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: mackerel-sidecar-injector-controller-manager
  namespace: mackerel-container-agent-sidecar-injector-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        image: mackerel-container-agent-sidecar-injector:test
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: mackerel-sidecar-injector-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mackerel-sidecar-injector-serving-cert
  namespace: mackerel-container-agent-sidecar-injector-system
spec:
  dnsNames:
  - mackerel-sidecar-injector-webhook-service.mackerel-container-agent-sidecar-injector-system.svc
  - mackerel-sidecar-injector-webhook-service.mackerel-container-agent-sidecar-injector-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: mackerel-sidecar-injector-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mackerel-sidecar-injector-selfsigned-issuer
  namespace: mackerel-container-agent-sidecar-injector-system
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: mackerel-container-agent-sidecar-injector-system/mackerel-sidecar-injector-serving-cert
  name: mackerel-sidecar-injector-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: mackerel-sidecar-injector-webhook-service
      namespace: mackerel-container-agent-sidecar-injector-system
      path: /mutate--v1-pod
  failurePolicy: Fail
  name: mutate.pod.mackerel.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
