name: exectute test

on: [push]
  workflow_dispatch:

jobs:
  kustomize:
    name: 'Kustomize'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Test'
        run: make test
      - name: 'Build'
        run: make docker-build
      - name: 'Build HelmTemplate'
        run: make helm-template
